name: BosMon
version: v0.2
slug: bosmon
description: BosMon ist ein innovatives Programm zum Dekodieren von ZVEI, FMS und Pocsag Telegrammen.
url: https://github.com/timniklas/addon-bosmon
image: ghcr.io/timniklas/addon-bosmon
ingress: true
ingress_port: 8099
ingress_stream: true
host_network: true
panel_icon: mdi:alarm-light
arch:
- amd64
options:
  key_name: ENTER NAME HERE
  key_serial: ENTER SERIAL HERE
schema:
  key_name: str
  key_serial: str
