name: BosMon
version: v0.5.5
slug: bosmon
description: BosMon ist ein innovatives Programm zum Dekodieren von ZVEI, FMS und Pocsag Telegrammen.
url: https://github.com/timniklas/addon-bosmon
image: ghcr.io/timniklas/addon-bosmon
ingress: true
ingress_stream: true
startup: services
panel_icon: mdi:alarm-light
arch:
- amd64
options:
  key_name: Tim Tester2
  key_serial: YA1QWI7JBBBEE572BPDC6RTAM
schema:
  key_name: str
  key_serial: str
ports:
  4001/tcp: null
  4002/tcp: null
  4003/tcp: null
  4004/tcp: null
ports_description:
  4001/tcp: ingress port 1 (optional)
  4002/tcp: ingress port 2 (optional)
  4003/tcp: ingress port 3 (optional)
  4004/tcp: ingress port 4 (optional)
