name: BosMon
version: v0.3.6
slug: bosmon
description: BosMon ist ein innovatives Programm zum Dekodieren von ZVEI, FMS und Pocsag Telegrammen.
url: https://github.com/timniklas/addon-bosmon
image: ghcr.io/timniklas/addon-bosmon
ingress: true
ingress_stream: true
startup: services
panel_icon: mdi:alarm-light
arch:
- amd64
options:
  key_name: Tim Tester2
  key_serial: YA1QWI7JBBBEE572BPDC6RTAM
schema:
  key_name: str
  key_serial: str
