name: BosMon
version: v1.1.2
slug: bosmon
description: BosMon ist ein innovatives Programm zum Dekodieren von ZVEI, FMS und Pocsag Telegrammen.
url: https://github.com/timniklas/addon-bosmon
image: ghcr.io/timniklas/addon-bosmon
ingress: true
ingress_stream: true
startup: services
panel_icon: mdi:alarm-light
arch:
- amd64
options:
  display_resolution: 1280x720
schema:
  key_name: str
  key_serial: str
  display_resolution: str
ports:
  80/tcp: null
ports_description:
  80/tcp: Webserver (optional)
