name: BosMon RTL-SDR
version: v1.2.3
slug: bosmon-rtlsdr
description: RTL-SDR Pocsag receiver
url: https://github.com/timniklas/addon-bosmon
image: ghcr.io/timniklas/addon-bosmon-rtlsdr
startup: services
arch:
- amd64
options:
  frequency: 439.9875
  gain: 100
schema:
  device: "device"
  frequency: "float"
  gain: "int"
  bosmon_url: "url"
  bosmon_username: "match([a-zA-Z0-9_]+)"
  bosmon_password: "password"
  bosmon_endpoint: "match([a-zA-Z0-9_]+)"
